apiVersion: apps/v1
kind: Deployment
metadata:
  name: openchecker-agent
  namespace: openchecker
  labels:
    app: openchecker-agent
spec:
  replicas: 3
  selector:
    matchLabels:
      app: openchecker-agent
  template:
    metadata:
      labels:
        app: openchecker-agent
    spec:
      containers:
      - name: openchecker-agent
        image: guoqiangqi/openchecker:v0.21
        imagePullPolicy: Always
        command: ["python", "-u", "openchecker/agent.py"]

        volumeMounts:
        - name: config-volume
          mountPath: /app/config/
      volumes:
      - name: config-volume
        persistentVolumeClaim:
          claimName: openchecker-pvc