apiVersion: apps/v1
kind: Deployment
metadata:
  name: openchecker-test-main
  namespace: openchecker
  labels:
    app: openchecker-test-main
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openchecker-test-main
  template:
    metadata:
      labels:
        app: openchecker-test-main
    spec:
      containers:
      - name: openchecker-test-main
        image: guoqiangqi/openchecker:v0.22
        imagePullPolicy: Always
        command: ["python", "-u", "openchecker/main.py"]
        ports:
        - containerPort: 80

        volumeMounts:
        - name: config-volume
          mountPath: /app/config
      volumes:
      - name: config-volume
        persistentVolumeClaim:
          claimName: openchecker-test-pvc