apiVersion: v1
kind: Service
metadata:
  name: openchecker-test-main-service
  namespace: openchecker
spec:
  selector:
    app: openchecker-test-main
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: openchecker-test-main-ingress
  namespace: openchecker
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt-dns01
spec:
  tls:
  - hosts:
    - openchecker-test.mlops.pub
    secretName: openchecker-test-mlops-pub-tls
  rules:
  - host: openchecker-test.mlops.pub
    http:
      paths:
      - path: /
        backend:
          service:
            name: openchecker-test-main-service
            port:
              number: 80
        pathType: Prefix