
apiVersion: v1
kind: PersistentVolume
metadata:
  name: openchecker-pv
  namespace: openchecker
spec:
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-client
  nfs:
    server: 192.168.0.110
    path: /nfs_provisioner_data/openchecker-data/config

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: openchecker-pvc
  namespace: openchecker
  annotations: {}
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi