
apiVersion: v1
kind: PersistentVolume
metadata:
  name: openchecker-pv
  namespace: openchecker
  labels:
    type: local
spec:
  storageClassName: local-storage
  #claimRef:
  #  name: postgres-pvc
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /openchecker-data/config
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8s-node01
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openchecker-pvc
  namespace: openchecker
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
