apiVersion: v1
kind: Service
metadata:
  name: compass-proxy
  namespace: compass
spec:
  externalName: sonarqube.mlops.pub
  type: ExternalName

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS # 指定后端协议为https
    nginx.ingress.kubernetes.io/upstream-vhost: sonarqube.mlops.pub #指定转发上游的host为要代理的域名
  name: compass-ingress
  namespace: compass
spec:
  tls:
  - hosts:
    - oss-compass.org
    secretName: compass-ingress-secret
  rules:
  - host: oss-compass.org
    http:
      paths:
      - backend:
          service:
            name: compass-proxy
            port:
              number: 443
        path: /
        pathType: ImplementationSpecific