apiVersion: v1
kind: Service
metadata:
  name: compass-proxy
  namespace: compass
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  type: ClusterIP

---

apiVersion: v1
kind: Endpoints
metadata:
  name: compass-proxy
  namespace: compass
subsets:
- addresses:
  - ip: 106.12.68.99
  ports:
  - name: http
    port: 80
    protocol: TCP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: HTTP # 指定后端协议为http
    nginx.ingress.kubernetes.io/proxy-body-size: "16m"
  name: compass-ingress
  namespace: compass
spec:
  tls:
  - hosts:
    - oss-compass.org
    secretName: compass-ingress-secret
  rules:
  - host: oss-compass.org
    http:
      paths:
      - backend:
          service:
            name: compass-proxy
            port:
              number: 80
        path: /
        pathType: Prefix