apiVersion: v1
kind: Service
metadata:
  name: compass-insight-org-proxy
  namespace: compass
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8788
  type: ClusterIP

---

apiVersion: v1
kind: Endpoints
metadata:
  name: compass-insight-org-proxy
  namespace: compass
subsets:
- addresses:
  - ip: 49.0.253.31
  ports:
  - name: http
    port: 8788
    protocol: TCP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: HTTP # 指定后端协议为http
    nginx.ingress.kubernetes.io/proxy-body-size: "16m"
    nginx.ingress.kubernetes.io/limit-rps: "0"
    nginx.ingress.kubernetes.io/limit-burst-multiplier: "0"
  name: compass-insight-org-ingress
  namespace: compass
spec:
  tls:
  - hosts:
    - insight.oss-compass.org
    secretName: compass-ingress-secret
  rules:
  - host: insight.oss-compass.org
    http:
      paths:
      - backend:
          service:
            name: compass-insight-org-proxy
            port:
              number: 80
        path: /
        pathType: Prefix